# NUMPY

In [1]:
pip install numpy

     |████████████████████████████████| 17.6 MB 2.1 MB/s 
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [8]:
a_list = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    ]
print(a_list)
print(a_list[1][1])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
6


In [15]:
a_np = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    ])

print(a_np) # array numpy jau nustato, kad 2d matrica ir print gaunasi toks
print(type(a_np))
print(a_np[1][1]) # 6 isgauname taip pat, kaip su list'u 
print(a_np[1,1]) # galima 6 ir isgauti taip
print([row[1] for row in a_list])
print(a_np[:,1]) # visa vertikalia eile
print(a_np[:2,1]) 
print(a_np[:2,1:3]) 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
6
6
[2, 6, 10]
[ 2  6 10]
[2 6]
[[2 3]
 [6 7]]


In [16]:
a_np.shape

(3, 4)

# 1D array

In [20]:
array_1d = np.array([1,5,7,9,71,14])

In [21]:
print(array_1d.shape) # grazina tuple formato duomenis. Formoje yra 6 skaiciai
print(len(array_1d))

(6,)
6


In [22]:
print(array_1d)

[ 1  5  7  9 71 14]


# 3D array

In [25]:
arr_3d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
        ]
    ]
)

In [26]:
print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [27]:
np.random.randn(2,2) #sukuria tokios formos duomenis. randn - atsitiktiniai skaiciai

array([[0.60590717, 0.14629804],
       [1.45332573, 0.08573517]])

# Numpy operations

In [28]:
py_list = [1,2,3,4,5]
print(py_list * 3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [29]:
np_array = np.array([1,2,3,4,5])

In [30]:
print(np_array*3)

[ 3  6  9 12 15]


In [31]:
print(np_array/3)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [32]:
print(np_array**3)

[  1   8  27  64 125]


In [33]:
print(py_list)

[1, 2, 3, 4, 5]


In [35]:
np_array[2:4] = 100 #apkeisti reiksme
print(np_array)
np_array[2:4] = [100, 200] # dydziai kiek ko pridedam turi sutapti su musu shape'u 
print(np_array)
np_array[2:4] = [100, 200]

[  1   2 100 100   5]
[  1   2 100 200   5]


# NUMPY SPEED

In [36]:
size = 100000

In [37]:
py_list = list(range(size))

In [39]:
np_arr = np.arange(size)

In [40]:
%%timeit #paskaiciuoja trukme skaiciavimu
list_rez = []
for number in py_list:
    list_rez.append(number * 10)

10.8 ms ± 546 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [41]:
%%timeit

np_rez = np_arr * 10

64.6 µs ± 938 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# RESHAPE

In [43]:
np_array = np.arange(0,100,2)
print(np_array)
print(np_array.shape)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)


In [44]:
print(np_array.reshape(5,10))

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [46]:
print(np_array.reshape((2,5,5)))

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [48]:
print(np_array.reshape((10,5,-1)))

[[[ 0]
  [ 2]
  [ 4]
  [ 6]
  [ 8]]

 [[10]
  [12]
  [14]
  [16]
  [18]]

 [[20]
  [22]
  [24]
  [26]
  [28]]

 [[30]
  [32]
  [34]
  [36]
  [38]]

 [[40]
  [42]
  [44]
  [46]
  [48]]

 [[50]
  [52]
  [54]
  [56]
  [58]]

 [[60]
  [62]
  [64]
  [66]
  [68]]

 [[70]
  [72]
  [74]
  [76]
  [78]]

 [[80]
  [82]
  [84]
  [86]
  [88]]

 [[90]
  [92]
  [94]
  [96]
  [98]]]
